# -*- coding: utf-8 -*-
"""MPPT-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16K_gQ-0EPbNMNx_zTW1lYDOQVgIFf35v
"""

import numpy as np
import matplotlib.pyplot as plt

# =========================
# MPPT PARAMETERS
# =========================
eps = 0.0005
dD = 5e-5
CR = 200

# =========================
# SIMULATION PARAMETERS
# =========================
dt = 5e-6
N = 2000000
t = np.arange(N) * dt

# =========================
# BOOST CONVERTER
# =========================
L = 1e-3
Cout = 470e-6
Rout = 50

# =========================
# PV PARAMETERS (STATIC)
# =========================
Voc = 40
Iscstc = 8
Gstc = 1000
G = 800
Isc = Iscstc *(G/Gstc)

# =========================
# STATE VARIABLES
# =========================
D = np.zeros(N)
IL = np.zeros(N)
Vpv = np.zeros(N)
Vout = np.zeros(N)
Ppv = np.zeros(N)

# =========================
# MPPT STORAGE
# =========================
AP1 = np.zeros(CR)
AP2 = np.zeros(CR)

# =========================
# INITIAL CONDITIONS
# =========================
D[0] = 0.646
IL[0] = 0.0
Vout[0] = 0.0
Vpv[0] = Voc
Ppv[0] = 0.0

j = 0

# =========================
# MAIN LOOP
# =========================
for k in range(1, N):

    # Hold duty constant by default
    D[k] = D[k-1]

    # -------------------------
    # PV VOLTAGE (STATIC I–V)
    # -------------------------
    Vpv[k] = Voc * (1 - IL[k-1] / Isc)
    Vpv[k] = np.clip(Vpv[k], 0, Voc)

    # -------------------------
    # BOOST INDUCTOR
    # -------------------------
    IL_slope = (Vpv[k-1] - (1 - D[k-1]) * Vout[k-1]) / L
    IL[k] = IL[k-1] + dt * IL_slope
    IL[k] = max(IL[k], 0)
    IL[k] = min(max(IL[k],0), Isc)

    # -------------------------
    # OUTPUT CAPACITOR
    # -------------------------
    Vout_slope = ((1 - D[k-1]) * IL[k-1] - Vout[k-1] / Rout) / Cout
    Vout[k] = Vout[k-1] + dt * Vout_slope
    Vout[k] = max(Vout[k], 0)

    # -------------------------
    # POWER
    # -------------------------
    Ppv[k] = Vpv[k] * IL[k]
    AP2[j] = Ppv[k]

    # -------------------------
    # MPPT (P&O)
    # -------------------------
    if j == CR - 1:
        Pnew = np.mean(AP2)
        Pold = np.mean(AP1)

        if abs(Pnew - Pold) >= eps:
            if Pnew < Pold:
                dD = -dD

        D[k] = np.clip(D[k] + dD, 0.05, 0.9)

        AP1[:] = AP2
        j = 0
    else:
        j += 1

# =========================
# PLOTTING
# =========================
plt.figure(figsize=(12, 7))
plt.plot(t, Vpv, label="PV Voltage (V)")
plt.plot(t, IL, label="PV Current (A)")
plt.plot(t, Ppv, label="PV Power (W)")
plt.plot(t, D, label="Duty cycle")
plt.axhline(np.mean(Ppv[-3000:]) + eps, color='r', linestyle='--')
plt.axhline(np.mean(Ppv[-3000:]) - eps, color='r', linestyle='--')


plt.xlabel("Time (s)")
plt.ylabel("Value")
plt.title("Boost Converter with MPPT (Correct Averaged Model)")
plt.legend()
plt.grid(True)
plt.show()
plt.figure()
plt.plot(Vpv, Ppv)
plt.xlabel("PV Voltage (V)")
plt.ylabel("PV Power (W)")
plt.title("MPPT Operating Points on PV Curve")
plt.grid()
plt.show()